spring:
  security:
    user:
      name:
      password:

  datasource:

    url: ${MYSQL_URL}
    driver-class-name: ${MYSQL_DRIVER}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWD}
#  h2:
#    console.enabled: true
#    console:
#      path: /h2-console
#      settings:
#        trace: false
#        web-allow-others: false

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: false
    hibernate:
      ddl-auto: update
    open-in-view: true
  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${EMAIL_USERNAME}
#    password: ${EMAIL_PASSWORD}
    host: localhost
    port: 1025
    username: hello
    password: hello
    properties:
      mail:
        smtp:
          ssl:
            trust: "*"
          auth: true
          starttls:
            enable: true
          connectiontimeout: 5000
          timeout: 3000
          writetimeout: 5000

  thymeleaf: # Thymeleaf
    cache: false
    mode: HTML
    encoding: UTF-8
    prefix: file:src/main/resources/templates/
    resources:
      static-locations: file:src/main/resources/static/
      cache:
        period: 0